### PR TITLE
Now absolutely all threads have names.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Names for job threads are looking like this:

    #<SB-THREAD:THREAD "Cron ULTRALISP/CRON::PERFORM-CHECKS (started at 2021-09-14 22:05:00)" RUNNING {100703ECB3}>

Also, jobs dispatcher was protected with *cron-dispatcher-processing* lock.

### CODE REVIEW

**Comment by vindarel** [comment]
Thanks!

If you have more changes I'll give you push rights, this must be a collectively maintained repository.

**Comment by svetlyak40wt** [comment]
I want to change logging from a custom log function to the log4cl. What do you think, @vindarel?

**Comment by svetlyak40wt** [comment]
Having push rights would be cool, because cron is the heart of Ultralisp's machinery :)

**Comment by vindarel** [comment]
Does it have a custom log function? Oh indeed^^ Invite sent (you'll carry on sending PRs so we can follow of course).

ps: there's a changelog entry in the readme.

**Pull request merged**
